#!/bin/sh

git clone https://github.com/danangan/progin.git
git clone https://github.com/pradita72/II3160--Pemrograman-Integratif-.git
git clone https://oliviatan@bitbucket.org/oliviatan/web-service.git
git clone https://github.com/prama13/18211037.git
git clone https://github.com/khairaniummah/BintangAdinandra.git
git clone https://github.com/adhelaip/IPT-Assignments.git
git clone https://github.com/ningenis/Pemrograman-Intergratif.git
git clone https://github.com/WidyaSTI/Web-Service.git
git clone https://github.com/khairaniummah/Workspace.git
git clone https://github.com/cahgantcore/Progint.git
git clone https://github.com/dannypranoto93/ConvertXML.git
git clone https://github.com/stefiotampan/testPHP2.git
git clone https://gilangr@bitbucket.org/gilangr/pemrograman_integratif.git
git clone https://github.com/muh-fajrin/18211010-18211035.git
git clone https://github.com/haryaputra/TugasProgIn.git
git clone https://github.com/dhendiii/Tugas-Protif-2.git
git clone https://github.com/afaizn/Protif.git
git clone https://emfatoni@bitbucket.org/emfatoni/pemrograman-integratif.git
git clone https://github.com/nicolasruslim/II3160-Pemograman-Integratif.git
git clone https://github.com/abrahamwk/II3160-Tugas1-Tugas2.git
git clone https://github.com//mike2kevin/nyoba.git
git clone https://raosan@bitbucket.org/raosan/progin.git
git clone https://christianhendy@bitbucket.org/christianhendy/tugas-2-pemrograman-integratif.git
git clone https://github.com/khairaniummah/II3160-Tugas2-18211055-18211026.git
git clone https://github.com/khairaniummah/BernadetteVina.git
git clone https://github.com/andyprimawan/habib-andy.git
git clone https://github.com/khairaniummah/II3160-18211003-18211050.git
